# Practical 01: Dataset Ingestion, Inspection & Descriptive Statistics with Pandas

**UNIT 1: Introduction to Big Data and Large Dataset Handling**

**Problem Statement:** Write a Python program using Pandas to load a structured dataset (CSV/JSON), display its first 5 rows, last 5 rows, dimensions (shape), column names, and data types with info(). Generate comprehensive summary statistics of all numeric and categorical attributes using describe(include='all').

In [1]:
import io
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None, "display.width", 200)

rg = np.random.default_rng(99)
n = 220
original = pd.DataFrame({
    "Order ID": np.arange(1001, 1001 + n),
    "Customer Name": [f"Buyer_{i:03d}" for i in rg.integers(1, 55, n)],
    "City": rg.choice(["Kolkata", "Patna", "Ranchi", "Delhi", "Lucknow", "Surat"], n),
    "Product Category": rg.choice(["Electronics", "Clothing", "Groceries", "Furniture", "Toys"], n),
    "Quantity": rg.integers(1, 10, n),
    "Unit Price": np.round(rg.uniform(120, 5500, n), 2),
    "Discount %": rg.choice([0, 5, 10, 15, 20], n),
    "Order Date": pd.date_range("2025-04-10", periods=n, freq="D").strftime("%Y-%m-%d"),
})

csv_stream = io.StringIO()
original.to_csv(csv_stream, index=False)
csv_stream.seek(0)
json_stream = io.StringIO(original.to_json(orient="records"))

frame = pd.read_csv(csv_stream)
print("Dataset loaded successfully!")

print(frame.head())

print(frame.tail())

print("Shape (rows, columns):", frame.shape)
print("Column names:", frame.columns.tolist())

frame.info()

print(frame.describe(include='all'))

df_js = pd.read_json(json_stream)
print("JSON load – shape:", df_js.shape)
print(df_js.head())

Dataset loaded successfully!

   Order ID  Customer Name     City  Product Category  Quantity  Unit Price  Discount %  Order Date
0      1001      Buyer_052  Kolkata       Electronics         9     3609.22           5  2025-04-10
1      1002      Buyer_028  Lucknow         Groceries         9     2604.05          20  2025-04-11
2      1003      Buyer_041    Delhi          Clothing         8     2609.10          10  2025-04-12
3      1004      Buyer_031  Kolkata          Clothing         3     2759.69          15  2025-04-13
4      1005      Buyer_010  Lucknow         Furniture         2     2388.64           5  2025-04-14

     Order ID  Customer Name     City  Product Category  Quantity  Unit Price  Discount %  Order Date
215      1216      Buyer_019    Patna         Furniture         6     3855.40           0  2025-11-11
216      1217      Buyer_019  Kolkata       Electronics         8     4834.56          10  2025-11-12
217      1218      Buyer_042  Lucknow         Furniture         8     5362.28          20  2025-11-13
218      1219      Buyer_027    Delhi         Furniture         9     3132.31          20  2025-11-14
219      1220      Buyer_014   Ranchi          Clothing         2     2764.50          15  2025-11-15

Shape (rows, columns): (220, 8)
Column names: ['Order ID', 'Customer Name', 'City', 'Product Category', 'Quantity', 'Unit Price', 'Discount %', 'Order Date']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 220 entries, 0 to 219
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order ID          220 non-null    int64
 1   Customer Name     220 non-null    object
 2   City              220 non-null    object
 3   Product Category  220 non-null    object
 4   Quantity          220 non-null    int64
 5   Unit Price        220 non-null    float64
 6   Discount %        220 non-null    int64
 7   Order Date        220 non-null    object
dtypes: float64(1), int64(3), object(4)
memory usage: 13.9+ KB

           Order ID  Customer Name     City  Product Category    Quantity   Unit Price  Discount %  Order Date
 count   220.000000            220      220               220  220.000000   220.000000  220.000000         220
unique          NaN             54        6                 5         NaN          NaN         NaN         220
   top          NaN      Buyer_028  Lucknow              Toys         NaN          NaN         NaN  2025-04-10
  freq          NaN             11       44                50         NaN          NaN         NaN           1
  mean  1110.500000            NaN      NaN               NaN    5.136364  2936.865591   10.545455         NaN
   std    63.652704            NaN      NaN               NaN    2.551666  1549.508475    7.194158         NaN
   min  1001.000000            NaN      NaN               NaN    1.000000   126.420000    0.000000         NaN
   25%  1055.750000            NaN      NaN               NaN    3.000000  1603.785000    5.000000         NaN
   50%  1110.500000            NaN      NaN               NaN    5.000000  2977.065000   10.000000         NaN
   75%  1165.250000            NaN      NaN               NaN    7.000000  4285.940000   15.000000         NaN
   max  1220.000000            NaN      NaN               NaN    9.000000  5494.740000   20.000000         NaN

JSON load – shape: (220, 8)

   Order ID  Customer Name     City  Product Category  Quantity  Unit Price  Discount %  Order Date
0      1001      Buyer_052  Kolkata       Electronics         9     3609.22           5  2025-04-10
1      1002      Buyer_028  Lucknow         Groceries         9     2604.05          20  2025-04-11
2      1003      Buyer_041    Delhi          Clothing         8     2609.10          10  2025-04-12
3      1004      Buyer_031  Kolkata          Clothing         3     2759.69          15  2025-04-13
4      1005      Buyer_010  Lucknow         Furniture         2     2388.64           5  2025-04-14